### PR TITLE
Tempo calculated with harmonic mean

### PR DESCRIPTION
**Pull request by George-Ogden**
I know that one of the issues was to maintain the tempo while merging, and this change will preserve that slightly. It calculates the harmonic mean of the tempi so that the time of the midi file remains the same.

### CODE REVIEW

**Comment by salu133445** [comment]
Thanks for the pull request. Although we should try tp support tempo change events, this is definitely preferable over using the first value of the tempo array for now. Also, I think we could use [`scipy.stats.hmean`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.hmean.html), right? Is there any difference in the implementations of `hmean`?

**Comment by George-Ogden** [comment]
> Thanks for the pull request. Although we should try tp support tempo change events, this is definitely preferable over using the first value of the tempo array for now. Also, I think we could use [`scipy.stats.hmean`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.hmean.html), right? Is there any difference in the implementations of `hmean`?

This is taken directly from the SciPy source code, so it would be possible to use the scipy.stats.hmean, this just reduces the dependencies of the project.

While tempo changes would be useful in the future, this is a temporary fix.

**Comment by salu133445** [comment]
Sure. We actually have scipy in our dependencies for saprse matrices I/O,
so we can use scipy directly.

George Ogden <notifications@github.com> 於 2021年1月22日 週五 下午10:52 寫道：

**Comment by George-Ogden** [comment]
Now, SciPy is used directly

**Comment by salu133445** [comment]
Looks good to me. Thanks again for the pull request.

**Comment by George-Ogden** [comment]
No worries. If I see any other bugs or enhancements, I'll put them through.

**Pull request merged**
